# Generated by Django 4.0.3 on 2022-03-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('beneficiario', models.CharField(max_length=100)),
                ('doador', models.CharField(max_length=100)),
                ('dat_criacao', models.DateTimeField(auto_now_add=True)),
                ('dat_alteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
