# Generated by Django 4.0.3 on 2022-03-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0002_alter_agendamento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='bool_encerrado',
            field=models.BooleanField(default=False),
        ),
    ]
